export const USER_CONNECT = 'USER_CONNECT';
export const USER_DISCONNECT = 'USER_DISCONNECT';
export const SIGNIN_FORM_FAILURE = 'SIGNIN_FORM_FAILURE';
export const REGISTER_FORM_FAILURE = 'REGISTER_FORM_FAILURE';
export const FORGOTPASSWORD_FORM_FAILURE = 'FORGOTPASSWORD_FORM_FAILURE';
export const FORGOTPASSWORD_FORM_SUCCESS = 'FORGOTPASSWORD_FORM_SUCCESS';