//USER
export const USER_BASIC = "ACCOUNT_BASIC";
export const USER_NAME = "USER_NAME";
export const USER_MAX_ACCOUNTS = "USER_MAX_ACCOUNTS";
//ACCOUNT
export const ACCOUNT_LIST_NAME = "ACCOUNT_LIST_NAME";
export const ACCOUNT_NAME = "ACCOUNT_NAME";
export const ACCOUNT_KEYS = "ACCOUNT_KEYS";
export const ACCOUNT_BLACKLIST = "ACCOUNT_BLACKLIST";
export const ACCOUNT_STATS = "ACCOUNT_STATS";
export const ACCOUNT_CACHE = "ACCOUNT_CACHE";
//CAMPAIGN
export const CAMPAIGN_LIST_NAME = "CAMPAIGN_LIST_NAME";
export const CAMPAIGN_NAME = "CAMPAIGN_NAME";